# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Vibe' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Vibe
  pod 'Firebase'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  
  target 'VibeTests' do
      inherit! :search_paths
      # Pods for testing
  end
  
  target 'VibeUITests' do
      inherit! :search_paths
      # Pods for testing
  end


end
